version: '3'

services:
  flask-app:
    image: ducdn01/python-flask-app:v1.0.0
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    